version: '3'
services:
  mirea-teacher-schedule-bot:
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./bot/db/data:/app/bot/db/data
    ports:
      - "127.0.0.1:8000:8000"